# barnacle cluster config.yaml
cluster: qsub
   -e {cluster.error}
   -o {cluster.output}
   -l nodes=1:ppn={cluster.n}
   -l mem={cluster.mem}
   -l walltime={cluster.time}
cluster-status: barnacle_status.py
max-jobs-per-second: 1
jobs: 16
keep-going: True
max-status-checks-per-second: 5
restart-times: 1
local-cores: 1
latency-wait: 90
